package pe.edu.solucionesweb.tramite.service;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import pe.edu.solucionesweb.tramite.dto.DerivacionRequest; import pe.edu.solucionesweb.tramite.model.*; import pe.edu.solucionesweb.tramite.repository.*; import java.time.*; import java.util.*;
@Service public class TramiteService {
 private final TramiteRepository tramites; private final AreaRepository areas; private final HistorialRepository historiales; private final DerivacionRepository derivaciones; private final NotificacionService notificaciones; private final Map<String,TipoTramite> tipos;
 public TramiteService(TramiteRepository t,AreaRepository a,HistorialRepository h,DerivacionRepository d,NotificacionService n,List<TipoTramite> estrategias){tramites=t;areas=a;historiales=h;derivaciones=d;notificaciones=n;tipos=new HashMap<>(); estrategias.forEach(e->tipos.put(e.nombre().toLowerCase(),e));}
 public List<Tramite> listar(String q){return q==null||q.isBlank()?tramites.findAll():tramites.findByAsuntoContainingIgnoreCaseOrSolicitanteContainingIgnoreCase(q,q);}
 public Tramite obtener(Long id){return tramites.findById(id).orElseThrow(()->new NoSuchElementException("No se encontró el trámite."));}
 @Transactional public Tramite registrar(Tramite t){ TipoTramite tipo=tipos.get(t.getTipoTramite().toLowerCase()); if(tipo==null) throw new IllegalArgumentException("Tipo de trámite no válido."); tipo.validar(t); if(t.getFechaRegistro()==null)t.setFechaRegistro(LocalDate.now()); if(t.getEstado()==null)t.setEstado(EstadoTramite.PENDIENTE); Tramite guardado=tramites.save(t); registrarHistorial(guardado,guardado.getEstado(),"Sistema","Trámite registrado",guardado.getAreaResponsable()); return guardado; }
 @Transactional public Tramite derivar(Long id,DerivacionRequest r){Tramite t=obtener(id); Area destino=areas.findById(r.areaDestinoId()).orElseThrow(()->new NoSuchElementException("No se encontró el área destino.")); t.setAreaResponsable(destino); t.setEstado(EstadoTramite.DERIVADO); Derivacion d=new Derivacion();d.setTramite(t);d.setAreaDestino(destino);d.setResponsable(r.responsable());d.setObservacion(r.observacion());d.setFecha(LocalDateTime.now());derivaciones.save(d); registrarHistorial(t,EstadoTramite.DERIVADO,r.responsable(),r.observacion(),destino); notificaciones.notificarDerivacion(t);return tramites.save(t);}
 @Transactional public Tramite actualizarEstado(Long id,EstadoTramite estado,String observacion){Tramite t=obtener(id);t.setEstado(estado);registrarHistorial(t,estado,"Funcionario",observacion,t.getAreaResponsable());return tramites.save(t);}
 public List<HistorialTramite> historial(Long id){obtener(id);return historiales.findByTramiteIdOrderByFechaAsc(id);} private void registrarHistorial(Tramite t,EstadoTramite e,String responsable,String observacion,Area a){HistorialTramite h=new HistorialTramite();h.setTramite(t);h.setEstado(e);h.setFecha(LocalDateTime.now());h.setResponsable(responsable);h.setObservacion(observacion);h.setArea(a);historiales.save(h);}
}
