spring.application.name=tramite-documentario
spring.datasource.url=jdbc:mysql://localhost:3306/tramite_documentario?createDatabaseIfNotExist=true&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=MySQL123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
